### ISSUE TITLE
Note: Login Interface Minor Bug

### ISSUE THREAD

**Issue by ravenCrown0627** [candycanegrunge/PutraEVENT#1]
1. Captured that the blank space for user to enter their email address and password might shift to another line when it is too long.
2. The password entered can make it invisible and give an option for user to view the password if necessary only.

Make sure to modify this before submission of project

![image](https://github.com/candycanegrunge/PutraEVENT_UI/assets/60862845/2114869a-ca50-446b-8cba-b65022905545)

**Comment by yew1129** [comment]
1. Solved
2. Only hide the password, no option to open for beta version
