### ISSUE TITLE
Feature: Forget Password

### ISSUE THREAD

**Issue by ravenCrown0627** [candycanegrunge/PutraEVENT#2]
The feature of giving the user to choose forget password option and send a password recovery email has a problem, where we can't identify whether the email entered by the user is registered in the system. 

Maybe just show with a toast state that "... email will be send within 3 mins" to let the user to notice that maybe the email entered is not in the database, so that they can try to register a new one.

**Comment by yew1129** [comment]
Noted that, due to time constraint, currently just let the user know that the email to reset password had been sent.
